### Default experiment hyperparameters 

# Transform
transforms:
  train:
    name: FlipCrop
    reprs: []
  valid:
    name: Identity
    reprs: []

# Dataset
datasets:
  train:
    name: CIFAR10
  valid:
    name: CIFAR10
